name: "Generate Ensemble"
on:
  workflow_dispatch:
  schedule:
    - cron: "15 11,23 * * 2,3"


jobs:
  ensemble:
  # if: github.repository_owner == 'european-modelling-hubs'
    runs-on: ubuntu-latest

    steps:
    # checkout repo
    - uses: actions/checkout@v3

    - uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - name: Installing dependencies
      run: |
        install.packages("remotes")
        remotes::install_github("infectious-disease-modeling-hubs/hubEnsembles")
        install.packages("dplyr")
        install.packages("jsonlite")
      shell: Rscript {0}

    - name: Generate Ensemble
      run: |
        # code here
        # Rscript code-folder/code.R

    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with: 
          add: 'data-folder'
          message: "Update ensemble data"
          default_author: github_actions
          push: true
