name: Persist Forecasts and meta-data changes to json

on:
  workflow_run:
    workflows: 
      - Hub Submission Validation (R)
    types:
      - completed

  workflow_dispatch:

jobs:



  call_from_other:
    uses: european-modelling-hubs/hub-tools/.github/workflows/store_the_changes.yml@main
    with:
      the-changes: "Pippo pluto e paperino"

      
  # update_json_changes:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Test Action
  #     run: |
  #       echo "The PR was merged"

  #   - name: Download workflow artifact
  #     uses: dawidd6/action-download-artifact@v2.11.0
  #     with:
  #       github_token: ${{ secrets.GITHUB_TOKEN }}
  #       workflow: validate-submission.yml
  #       run_id: ${{ github.event.workflow_run.id }}

  #   - name: Read the pr_num file
  #     id: pr_changes_reader
  #     uses: juliangruber/read-file-action@v1.0.0
  #     with:
  #       path: ./pr_changes/pr_changes.txt

  #   - name: Trace the changes
  #     run: | 
  #       echo "Changes: ${{ steps.pr_changes_reader.outputs.content }}"

  #   # Checkout the python tools repo
  #   # used to authenticate and validate the PR
  #   # -------------------------------------------      
  #   - name: checkout python tools repo
  #     uses: actions/checkout@v3
  #     with:
  #       token: ${{ secrets.GITHUB_TOKEN }}
  #       repository: 'european-modelling-hubs/hub-tools'
  #       ref: 'main'
  #       path: tools

    
  #   # Store changes 
  #   # -------------------------
  #   - name: Store Changes 
  #     env:
  #       data: ${{ steps.pr_changes_reader.outputs.content }}
  #     run: |
  #       echo ">>> Store changes to json"
  #       python ./tools/.github/scripts/utils/store_changes.py
     
